meta_product_name: "My Park"
meta_title: "My Park - Easy parking"
meta_description: "   Knowing where to park saves you time.
                You'll never be late for that business meeting
                or your best friend's dinner party again!"
meta_image: "logowhite.png" # should exist in `app/assets/images/`

